flags: {}
image:
  container:
    base: fpco/stack-run
    name: use-haskell-api
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/Palmik/bson-generic.git
    commit: e078def65d0dee1ea7e3205f445e47d5937851f3
docker:
  enable: false
extra-deps:
- bson-mapping-0.1.4.1
- compact-string-fix-0.3.2
- http-api-data-0.3.2
- servant-0.9.1.1
- servant-client-0.9.1.1
- servant-server-0.9.1.1
resolver: lts-7.10
